영감 공유하기 - LINK | TEXT
depromeet/ygtang-client pull request #423
Opened 2022-06-14 14:33 UTC by SenseCodeValue

## ⛳️작업 내용
- 공유된 영감을 message로 받아 State에 넣어주는 작업을 진행했습니다.

Native WebView 컴포넌트에서 onLoad, onLoadEnd, onProgress progress===1 모두 도전했지만 타이밍 맞추는 것에 실패했습니다.
따라서 handshake 방법을 차용하였습니다. 단계는 아래와 같습니다.
```
        1.Native가 WebView를 엽니다.
        2.WebView useDidMount가 되었을 경우,
          - { type: SHARE_WEB_MESSAGE_STATE, data: 'READY' }을 Native로 보냅니다.
          - ios | android에 맞는 target에 evnet를 달아줍니다.
        3.Native는 { type: SHARE_WEB_MESSAGE_STATE, data: 'READY' }를 받아 공유할 데이터를 쏘아줍니다.
        4.WebView는 setStateHandler로 데이터를 넘겨줍니다.
```

## 📸스크린샷
https://user-images.githubusercontent.com/59507527/173603021-1ba5eb1a-a353-4b24-ba84-5de5cc61c5d2.mov

## ⚡️사용 방법

### useDataShareMessage 사용법
선언부에 해당하는 state setter를 넘기면됩니다.
```ts 
export default function AddText() {
  useDataShareMessage(inspiringText.setValue);
}
```

## 📎레퍼런스
https://evanjin.oopy.io/react-native/webview
https://stackoverflow.com/questions/41160221/react-native-webview-postmessage-does-not-work

2022-06-15 10:16 UTC, ddarkr requested changes
👍👍👍 고생하셨어요! 오타 하나만 고쳐주셨으면 함당~

2022-06-15 10:16 UTC, ddarkr commented on src/components/add/LinkInput.tsx
> +export default function LinkInput({ initalLink, openGraph, saveOpenGraph }: LinkInputProps) {
```suggestion
export default function LinkInput({ initialLink, openGraph, saveOpenGraph }: LinkInputProps) {
```

영어 오타 변경 부탁드립니다~!

2022-06-15 14:19 UTC, positiveko approved these changes
너무너무 고생 많으셨어요 대윤님! 일단 기능이 이번주 내로 완성 되었음 좋겠는데, 집단지성의 도움 필요하시다거나.. 일손 필요하시면 언제든지 말씀주세요!

2022-06-15 14:19 UTC, positiveko commented on src/hooks/common/useDataShareMessage.ts
> +//        WebView는 setStateHandler로 데이터를 넘겨줍니다.
오... 좋은 방법인 것 같은데요? 👍🏻👍🏻👍🏻👍🏻 많은 고민이 묻어나는 방법이네요

2022-06-15 14:19 UTC, positiveko commented on src/hooks/common/useDataShareMessage.ts
> +  const handleMessage = (event: MessageEvent | any) => {
요거 이벤트가 any여야 하는 건 data 때문인거죠? 
일단 unknown으로 하고 아래 event.data 부분에서 타입가드로 한번 막아주는 건 어떨까요?

2022-06-18 16:21 UTC, SenseCodeValue commented on src/hooks/common/useDataShareMessage.ts
> +  const handleMessage = (event: MessageEvent | any) => {
적용했어요! 다시한번 리뷰 부탁드립니다! [3ec489f](https://github.com/depromeet/ygtang-client/pull/423/commits/3ec489fa722b843be5d8e0dc3fcf1f84db2967ee)

2022-06-18 16:21 UTC, SenseCodeValue commented on src/components/add/LinkInput.tsx
> +export default function LinkInput({ initalLink, openGraph, saveOpenGraph }: LinkInputProps) {
변경완료했습니다. [5bdf2af](https://github.com/depromeet/ygtang-client/pull/423/commits/5bdf2afbb3e9bc898e9edbec4e042edeb3be03fd)

2022-06-19 07:02 UTC, ddarkr approved these changes
👍👍👍👍 정말 수고하셨어요~~!!

2022-06-19 08:03 UTC, merged